Repository michalfita/packer-plugin-cross, pull requests merged in 2023-12, with the labels that each got.

#4 [FIxes #2] Prepare the repository rename
  .github/workflows/docker.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .goreleaser.yml
  Makefile
  README.md
  Vagrantfile
  boards/armv7/alpine.json
  boards/armv7/archlinuxarm-docker.pkr.hcl
  boards/armv8/archlinuxarm-docker.pkr.hcl
  boards/bananapi-r1/archlinuxarm.json
  boards/beaglebone-black/angstrom.json
  boards/beaglebone-black/archlinuxarm.json
  boards/beaglebone-black/debian.json
  boards/beaglebone-black/ubuntu.pkr.hcl
  boards/jetson-nano/ubuntu.json
  boards/odroid-u3/archlinuxarm.json
  boards/odroid-xu4/archlinuxarm.json
  boards/odroid-xu4/ubuntu.json
  boards/parallella/archlinuxarm.json
  boards/parallella/ubuntu.json
  boards/raspberry-pi-3/archlinuxarm.json
  boards/raspberry-pi-3/raspios-lite-arm64.json
  boards/raspberry-pi-4/archlinuxarm.pkr.hcl
  boards/raspberry-pi-4/ubuntu_server_20.04_arm64.json
  boards/raspberry-pi-4/ubuntu_server_20.04_arm64.pkr.hcl
  boards/raspberry-pi/archlinuxarm.json
  boards/raspberry-pi/raspbian-resize.json
  boards/raspberry-pi/raspbian.json
  boards/raspberry-pi/raspios-lite-arm.json
  boards/rock-4b/debos-radxa.pkr.hcl
  boards/wandboard/archlinuxarm.json
  builder/builder.go
  builder/builder.hcl2spec.go
  builder/step_mount_image.go
  builder/step_setup_chroot.go
  docker/Dockerfile
  go.mod
  main.go
  version/version.go
Labels: enhancement

#5 [Fixes #2] Publish container to ghcr.io
  .github/workflows/archlinuxarm-armv7-docker.yml
  .github/workflows/archlinuxarm-armv8-docker.yml
  .github/workflows/docker.yml
  README.md
  boards/armv7/archlinuxarm-docker.pkr.hcl
  boards/armv8/archlinuxarm-docker.pkr.hcl
  builder/artifact.go
  docker/Dockerfile
Labels: bug

#11 Fix: Explicitly set packages write permissions
  .github/workflows/docker.yml
Labels: bug

#20 Fixes to the `README.md`: restore notice boxes
  README.md
Labels: bug, documentation, chore
